### ISSUE TITLE
setSizeFull doesn't work

### ISSUE THREAD

**Issue by anezthes** [vaadin/vaadin-dialog-flow#103]
Use case: full-screen dialogs (mobile).

Can't add class names to the dialog, as it doesn't implement `HasStyle`.

Via `dialog.getElement().getClassList().add("custom");` you can add class names to the dialog, but not the overlay (nor the component renderer). Thus, I have to use `position: fixed;` on the actual contents of the dialog to make it fullscreen.

**Comment by anezthes** [comment]
> Thus, I have to use **position: fixed;** on the actual contents of the dialog to make it fullscreen.

Which seems to have a lot of issues on iOS.

**Comment by web-padawan** [comment]
Fixed by #147 and will be available in the upcoming Vaadin 14.2 as a behavior altering fix.
