### ISSUE TITLE
Make it clear that setWidth & setWidth relative sizing to the viewport

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-dialog-flow#123]
Make it clear that setWidth & setWidth do not support relative units because of the dom structure, or better yet, make it support view port relative sizes.

I would rather see `dialog.setHeight("90%");` to throw an exception than silently failing. Also the JavaDoc of `com.vaadin.flow.component.dialog.Dialog.setHeight(String)` should have note thet setting relative sizes does not work.

![image](https://user-images.githubusercontent.com/886091/54617480-03aa6c00-4a6a-11e9-9734-fc4e7d2f1f4f.png)

Minimal code to reproduce the problem:
```java
Dialog dialog = new Dialog(new Paragraph("Here's my fancy dialog which I would like to fill 90% x 90% of the window."));

dialog.setWidth("90%");
dialog.setHeight("90%");

dialog.open();
```

**Comment by Wnt** [comment]
As a workaround you can specify the size in `vw` and `vh` units.
```
dialog.setWidth("80vw");
dialog.setHeight("80vh");
```

**Comment by rolfsmeds** [comment]
No longer an issue as of https://github.com/vaadin/vaadin-dialog/issues/132
