### ISSUE TITLE
Change position of dialog via Java API

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-dialog-flow#138]
Our dialog's position cannot be changed via Java API out of the box. This should be provided, since not all dialogues needed to be centered.

Following methods as a proposal:
`setPositionXYZ(int value, Unit unit)`, where XYZ could be Top, Left, Bottom, Right. Sets the position of the dialog respective to the set values, as if the user uses css to position the dialog (like "top: 20px; left: 10px")

`setPositionOutsideOfViewportAllowed(boolean)`. If set to false, the dialog position will be modified to prevent, that the dialog is set outside of the viewport. This method is an optional convenience method, since it can be calculated by the developer if needed.

```
// creating a dialog that is placed on 200,500 from the viewport
Dialog d = new Dialog();
d.setPositionLeft(200, Unit.PIXEL);
d.setPositionTop(500, Unit.PIXEL);
d.setPositionOutsideOfViewportAllowed(false); 
d.open();

// move it around
d.setPositionLeft(300, Unit.PIXEL); 
```

**Comment by mvysny** [comment]
I would also appreciate to have a `dialog.setPositionRelativeTo(Component)` - that would allow me to implement e.g. a ComboBox-ish component easily, by simply positioning the Dialog right below a button acting as a combo box (e.g. when implementing some kind of Popup tree picker).

**Comment by web-padawan** [comment]
Closing in favor of #154. Now when we are working on draggable dialog support for the upcoming 14.2 this actually makes more sense. Let's use that issue, I linked this one from there.
