### ISSUE TITLE
Add a note that 'setWidth' sets a width to a 'flow-component-renderer', not an overlay/dialog itself

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-dialog-flow#139]
```
Dialog dialog = new Dialog();
dialog.add(new Label("Close me with the esc-key or an outside click"));
dialog.setWidth("80px");
```
Sets the width of the div inside the flow-component-renderer, but not the dialog itself

This (as turned out )is in line with the acceptance criteria of a `setWidth` https://github.com/vaadin/vaadin-dialog-flow/issues/35#issuecomment-381064459

Though, it would be nice to add a mention about this behavior to JavaDocs, since it's not what a user expects by default.

**Comment by web-padawan** [comment]
Fixed by #147 and will be included to `2.1` minor release as a behavior altering fix.
