### ISSUE TITLE
An opened Dialog component does not disable the UI to which it belongs.

### ISSUE THREAD

**Issue by daniel-scoalainformala** [vaadin/vaadin-dialog-flow#140]
### Description
An opened Dialog component does not actually disable the UI to which it belongs. The Dialog's parent UI **remains active server-side** and can be interacted with, if the Dialog is removed from the DOM by using DevTools.

### Expected outcome
The parent UI of a Dialog should remain disabled **server-side** while a Dialog is opened, and not be interactive.

### Actual outcome
The parent UI can be enabled client-side by using Browser Developer Tools: delete the Dialog, disable "pointer-events: none" inline style on BODY element

### Live Demo

```
Dialog dialog = new Dialog();
dialog.add("this dialog");
dialog.setCloseOnOutsideClick(false);
dialog.setCloseOnEsc(false);
		
dialog.open();	
```

### Steps to reproduce
1. Create a Dialog
2. Disable closing the dialog on ESC and Outside Click
3. Open the Dialog
4. Enter Developer Tools
5. Delete the Dialog (remove it from the DOM)
6. Disable the "pointer-events: none" inline style from the BODY element

### Browsers Affected
- [x ] Chrome
- [ x] Firefox
- [ x] Safari
- [ x] Edge
- [ x] IE 11
- [ x] iOS Safari
- [ x] Android Chrome

**Comment by DiegoCardoso** [comment]
The desired behaviour looks more like an enhancement rather than a bug.

It can be implemented by listening to the opened-changed dialog event in order to disable/enable the view. However, Flow doesn't allow that an element with an explicitly disabled ascendent to be set as enabled, so in oder to make it work the `UI` can't be disabled but rather the view and the Dialog can't be attached to it, otherwise it would also be disabled.

The implementation can be something like this:

```java
Dialog dialog = new Dialog();
dialog.setCloseOnOutsideClick(false);
dialog.setCloseOnEsc(false);

dialog.addOpenedChangeListener(e -> {
    if (!e.isFromClient()) {
        this.setEnabled(!dialog.isOpened());
    }
});
```

To enable this behaviour, there would be needed proper solution in Flow to allow us to disable/lock the whole UI but a subtree.

**Comment by GillHawk** [comment]
Proposed workaround solution that works also with multiple opened modal dialogs:


```
public class CustomDialog extends Dialog {

	@Override
	public void open() {
		onOpenDialog();
		
		super.open();
	}
	
	@Override
	public void close() {
		super.close();
		
		onCloseDialog();
	}

	private void onOpenDialog() {
		// on open Dialog, disable root component
		setRootComponentEnabled(false);
	}

	private void onCloseDialog() {
		// on close Dialog, enable root component if there are no more dialogs opened
		List<Component> cmps = UI.getCurrent().getChildren().collect(Collectors.toList());
		int cntOtherDialogs = 0;

		for (Component cmp : cmps) {
			if (cmp instanceof Dialog && (cmp != this)) {
				cntOtherDialogs++;
			}
		}

		// no other dialogs, enable root component
		if (cntOtherDialogs < 1) {
			setRootComponentEnabled(true);
		}
	}

	/** call setEnabled on root component of current UI */
	private static void setRootComponentEnabled(boolean enabled) {
		UI.getCurrent().getChildren().filter(c -> c instanceof HasEnabled).findFirst().ifPresent(c -> ((HasEnabled)c).setEnabled(enabled));		
	}
}
```
