### ISSUE TITLE
Add support for resizable dialogs

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-dialog-flow#141]
Please add support for user-resizable dialogs

**Comment by web-padawan** [comment]
Depends on https://github.com/vaadin/vaadin-dialog/issues/132

**Comment by DiegoCardoso** [comment]
WIP https://github.com/vaadin/vaadin-dialog/pull/139

**Comment by TatuLund** [comment]
Should this be closed by https://github.com/vaadin/vaadin-dialog-flow/pull/153 ?

**Comment by web-padawan** [comment]
Yes, thanks. Closing as done by #153, will  be included to the upcoming Vaadin 14.2.
