### ISSUE TITLE
Add support for non-modal dialogs

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-dialog-flow#142]
Please add support for non-modal dialogs. My use-case is that an user is editing a web page, and she should be able to see the preview of the web page in a non-modal dialog (so that she can interact with the editor components).

**Comment by TatuLund** [comment]
Should this be closed by https://github.com/vaadin/vaadin-dialog-flow/pull/153 ?

**Comment by web-padawan** [comment]
Closing as done by #153, will be included to the upcoming Vaadin 14.2.
