### ISSUE TITLE
setWidth and setHeight either not working, or are wrongly documented

### ISSUE THREAD

**Issue by alump** [vaadin/vaadin-dialog-flow#144]
**Steps to reproduce:**
1. Go to https://vaadin.com/components/vaadin-dialog/java-examples
2. Open the dialog of the first demo (that sets width to 400px and height to 150px)
3. Check size of the dialog

<img width="715" alt="Screen Shot 2019-12-11 at 14 15 43" src="https://user-images.githubusercontent.com/1378660/70666099-d23e8580-1c22-11ea-9b2e-0c1b94610d39.png">

**Expected outcome:**
Dialog should be 400x150 px, as that is how setWidth and setHeight are defined in JavaDoc

**Actual outcome:**
Dialog is 448x198 px, because box-sizing is wrong in default theming? Or there is no JavaDoc that tells that additional random pixels will be added to these values depending on padding values in theming.

**Version:** Vaadin 14.1.2

**Comment by anasmi** [comment]
This is pretty much the same as https://github.com/vaadin/vaadin-dialog-flow/issues/139

But fully agree - that's not expected

**Comment by web-padawan** [comment]
Fixed by #147 and will be included to `2.1` minor release as a behavior altering fix.
