### ISSUE TITLE
2.0 SNAPSHOT build fails

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin-dialog-flow#146]
Dialog 2.0-SNAPSHOT build in bender fails due to test failures. See the build history [here](https://bender.vaadin.com/viewType.html?buildTypeId=Flow_ComponentSnapshot_Dialog&tab=buildTypeHistoryList). It looks unstable in a way that every time new tests are failing. It should be investigated and fixed.

**Comment by web-padawan** [comment]
Seems to be passing since January 15. Closing, will re-open if the problem persists.
