### ISSUE TITLE
Dialog can only be dragged near the overlay edges

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-dialog-flow#165]
The Flow version of Dialog adds an internal, full-sized `div` [container](https://github.com/vaadin/vaadin-dialog-flow/blob/master/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L58) for all the dialog content, which prevents grabbing the dialog for dragging everywhere else but near the overlay edges (that aren't covered by the `div`).

Add a `grabbable` class (for example, naming tbd) to the `div` container and add support for grabbing an element with the marker at https://github.com/vaadin/vaadin-dialog/blob/master/src/vaadin-dialog-draggable-mixin.html#L30

**Comment by DiegoCardoso** [comment]
Closed by #166

**Comment by mvysny** [comment]
It would be good to have an API to mark a div as draggable, or have this thoroughly explained in the documentation. Currently it's not clear on how to e.g. create a title bar which would also drag the dialog: https://github.com/vaadin/vaadin-dialog-flow/issues/107

**Comment by tomivirkki** [comment]
@mvysny Documented in https://github.com/vaadin/vaadin-dialog-flow/blob/2.1/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L403-L406
