### ISSUE TITLE
In Safari, cursor changes to "text" while dragging the dialog

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/vaadin-dialog-flow#174]
**Version:** 14.2.0.alpha9

**Comment by martaolszewskatusiek** [comment]
A comment, coming from discussing with Onur: most likely a Safari issue; this misbehaviour does not happen in Chrome.

**Comment by tomivirkki** [comment]
Most likely a regression from this removal https://github.com/vaadin/vaadin-dialog/commit/645970fa1e752db391888f18805ca9fc99b73bc9#diff-e2b8dea15ec3b87f9028e5b2b193fc5eL32

**Comment by yuriy-fix** [comment]
Yeah, just have checked it. We should check `if (!isMobile)` then `preventDefault` on that line
