### ISSUE TITLE
Scrolling for vaadin-dialog-overlay not working for iPad(Safari/Chrome) Huawei tablet(Chrome)

### ISSUE THREAD

**Issue by chirastefan** [vaadin/vaadin-dialog-flow#201]
The scrolling for vaadin-dialog-overlay component for iPad(Chrome/Safari) Huawei tablet(Chrome) is not working, it only works with 2 fingers and in that case, it's buggy.
I've tried adding `-webkit-overflow-scrolling: touch; and overflow: scroll` "to everything" as mentioned by somebody on the internet. Not working.
This https://github.com/vaadin/vaadin-dialog-flow/issues/196 is not related to this issue.

Modal structure:
<img width="806" alt="Screen Shot 2020-06-30 at 02 27 32" src="https://user-images.githubusercontent.com/16649178/86287903-bcf66c00-bbf1-11ea-8234-4a63ebbc516d.png">

![image](https://user-images.githubusercontent.com/16649178/86288450-9b49b480-bbf2-11ea-933b-fa92b3abb41d.png)

**Comment by DiegoCardoso** [comment]
Hi.

Could you share in which version of the component you are having this issue? (The platform version might be enough).

Thanks

**Comment by chirastefan** [comment]
Hello, I'm using Vaadin 14.2.0

**Comment by alvarezguille** [comment]
Hi @chirastefan could you try with 14.2.3? It has scrolling related fixes for dialog.

**Comment by chirastefan** [comment]
Hi, I will try it and let you know. Thank you.

**Comment by chirastefan** [comment]
I can confirm that this issue is fixed with version 14.2.3, Thanks.

**Comment by alvarezguille** [comment]
Great to hear that, I'll close the issue
