### ISSUE TITLE
Vertical resizing problem in Safari

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-dialog-flow#207]
## Vaadin version
14.2.3
## vaadin-dialog-flow version
2.1.2
## Description of the problem
One would expect to get a dialog with a TextArea filling it, and when done with Firefox and Chrome, that’s exactly the case. And the TextArea nicely follows with the dialog resize. With Safari the content is not being resized vertically, at all. In fact shrinking the dialog to be short enough, the TextArea sticks outside of the thing which should contain it.
Probably it's related to [this issue](https://github.com/vaadin/vaadin-dialog-flow/issues/204).

## Expected behavior
Safari should behave like the rest of the browsers

## Code to reproduce the issue:
```
    	Dialog basicDialog = new Dialog();
    	basicDialog.setResizable(true);
    	TextArea dialogText = new TextArea();
    	dialogText.setSizeFull();
    	basicDialog.add(dialogText);
    	Button openBasic = new Button("Open basic dialog");
    	openBasic.addClickListener(event -> {
    		basicDialog.open();
    	});
    	add(openBasic);
```

**Comment by web-padawan** [comment]
The bug appears to be similar to https://github.com/vaadin/vaadin-dialog-flow/issues/204#issuecomment-661874922
This one is also working properly in Safari 14 beta, but not in Safari 13.1.

However, setting `min-height: 100%` (which fixed #204) does not help in this case.

**Comment by web-padawan** [comment]
Created another reduced test case with native `<textarea>`: https://codepen.io/web-padawan/pen/MWKLvaz

### Safari 14

![Screenshot 2020-07-22 at 13 53 05](https://user-images.githubusercontent.com/10589913/88168248-d2741a00-cc22-11ea-85df-9ed06612da82.png)

### Safari TP 102

![Screenshot 2020-07-22 at 13 54 01](https://user-images.githubusercontent.com/10589913/88168269-da33be80-cc22-11ea-9774-f1e8c16cec56.png)

**Comment by web-padawan** [comment]
Another demo with Vaadin components, using `vaadin-dialog` 2.4.3, which shows the bug is still there:
https://glitch.com/edit/#!/prickle-shore-cast?path=index.html
https://prickle-shore-cast.glitch.me
