### ISSUE TITLE
Vaadin 17: Wrong dialog size

### ISSUE THREAD

**Issue by Springrbua** [vaadin/vaadin-dialog-flow#225]
We are using a `VertiacalLayout`, without the `padding` theme, inside a dialog. The `VerticalLayout` contains a title, a body and a button.
Since we upgraded to Vaadin 17, this dialog shows a vertical scrollbar:
Vaadin 14:
![image](https://user-images.githubusercontent.com/18258317/93051766-46e89980-f665-11ea-8bf3-0d68820862b8.png)
Vaadin 17:
![image](https://user-images.githubusercontent.com/18258317/93051797-54058880-f665-11ea-84c7-7349340e2843.png)

The issue seems to be related to #195. The [`display: inline`of the draggable-div](https://github.com/vaadin/vaadin-dialog-flow/blob/master/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L66) seems to cause an additional space at the top of the dialog, which causes it to display the scrollbar.

Reproduction:

1. Create a new Vaadin 17 Project
2. Create a view with the following content:
```
	Dialog dlg = new Dialog();
	VerticalLayout vl = new VerticalLayout();
	vl.setPadding(false);
	vl.add(new Span("Title"));
	vl.add(new Span("Body"));
	vl.add(new Button("OK"));
	dlg.add(vl);
	Button button = new Button("Open dialog", e -> dlg.open());
	add(button);
```
3. Execute the project and click the button to open the dialog.

**Comment by dyachera** [comment]
I had similar issue moving from 16 to 17 (https://vaadin.com/forum/thread/18425441/vaadin-17-dialog-change-issue). I was able to fix by adding theme with following:

```
[theme~="dms-dialog"] .draggable {
  display: flex !important;
}
```

You could probably also just add to dialog css to put it everywhere.  With your example above I got:

17 Without added css
![1](https://user-images.githubusercontent.com/28050035/93244020-0e28ed00-f757-11ea-9847-fa23553f823e.jpg)

17 With added
![2](https://user-images.githubusercontent.com/28050035/93244042-1719be80-f757-11ea-8b92-063de8ba606d.jpg)


Hope it helps, will be following this as well to see if there is better way
