### ISSUE TITLE
Bug: Draggable Dialog block text selection since Vaadin 14.3.6

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/vaadin-dialog-flow#228]
Vaadin 14.3.6

If it is used draggable dialog and you have formlayout with form item and that contains e.g. text field then:
- you cannot select text
- you cannot drag text to other input field as it is build-in feature of browser
- you cannot copy and paste to other input field by dragging by build-in feature of browser (drag + CTRL)
- ... what ever you want to do with selected text like search, copy, ...

Expected behavior is:
You can do that as before. So excluding vaadin text fields from dragging of dialog.

**Comment by netbeansuser2019** [comment]
#190
#191

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/vaadin-dialog-flow/pull/230
