### ISSUE TITLE
Dialog should implement HasSize

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-dialog-flow#35]

**Comment by jouni** [comment]
I heard this was going to be fixed soon, and I started wondering how exactly? There’s no client side API for this specifically, so how are you going to set the correct style properties on the `vaadin-dialog-overlay` element? I hope not by using `dialog.$.overlay`…

IMO, we should first implement this feature in `vaadin-dialog`, if it’s deemed necessary. At the moment, the way I see it working is that you size the content instead, not the dialog itself. That’s maybe backwards, but works for most use cases sufficiently.

**Comment by pleku** [comment]
Thanks for the heads up Jouni.

>I see it working is that you size the content instead, not the dialog itself. 

I see that we could make it set the size of the content and then thus size the dialog. It would still be very convenient for the server side users.

**Comment by pleku** [comment]
But I also wonder if we should somehow expose the `vaadin-dialog-overlay` element for any Element API operations via Flow, like would be needed here: https://github.com/vaadin/vaadin-dialog-flow/issues/28

**Comment by jouni** [comment]
> I see that we could make it set the size of the content and then thus size the dialog. It would still be very convenient for the server side users.

IMO that sounds unnecessary, and potentially confusing. Possibly convenient, I admit that. But if we add sizing support for the `vaadin-dialog` element, then you’d probably have to break the API.

> But I also wonder if we should somehow expose the vaadin-dialog-overlay element for any Element API operations via Flow, like would be needed here: #28

The use case of setting the `theme` attribute (#28) directly on the overlay element is a workaround. The `theme` attribute should propagate from the main `vaadin-dialog` element to the overlay. That’s been tracked here: https://github.com/vaadin/vaadin-dialog/issues/37

I haven’t heard of (and haven’t spent time thinking about) other use cases for accessing the overlay element.

**Comment by pleku** [comment]
### Acceptance Criteria
- Add `HasSize` to `Dialog`
  - the size should be applied to the `flow-component-renderer` / container element (?)
- Add a demo for sizing the dialog
