### ISSUE TITLE
addDialogCloseActionListener works only first time

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-dialog-flow#68]
To reproduce both scenarios I created dialog object on server-side and added `closeAction` listener.

a) When `addDialogCloseActionListener` is called, behind the scene the dialog is automatically attached to the page. Which can ruin some toher logic, when it's needed to attach the dialog to specific place.
b) After Dialog was closed first time and reopened `$0.$.overlay` is already another object, which doesn't listen to the needed events. So, the event is fired only 1 time. Moreover, this can cause mem leaks.

**Comment by denis-anisimov** [comment]
Thanks for good analysis and good description.

The `addDialogCloseActionListener` method implementation is really soooo weird.
You are totally right that there are many issues with it.
The very first thing which makes me confused is the method API.
I've been completely sure that I'm adding only a close listener without any additional action.
In reality one the listener is added the dialog cannot be closed anymore from the client side via clicking outside it or via `ESC`  button. And server side should call `close` method explicitly to close the dialog.
This is so no obvious that I spent a lot of time trying to understand the behavior.
