### ISSUE TITLE
Confirmation dialog" could contain some text and close with esc

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-dialog-flow#89]
Moved from Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-dialog/java-examples
"Confirmation dialog"

The demo would look much better if the dialog only contained something like 

You have unsaved changes that will be discarded if you navigate away.

[Discard Changes] [Cancel]
Also it's natural to bind Esc to "cancel"

**Comment by web-padawan** [comment]
Fixed by #208
